version: 2.1
orbs:
node: circleci/node@5.0.2
aws-cli: circleci/aws-cli@1.3.1
jobs:
build:
 docker:
   - image: "cimg/node:14.15"
 steps:
   - node/install
   - checkout
   - run:
       name: Front-End Install
       command: |
         npm run frontend:install
   - run:
       name: Back-End Install
       command: |
         npm run backend:install
   - run:
       name: Front-End Build
       command: |
         npm run frontend:build
   - run:
       name: Back-End Build
       command: |
         npm run backend:build

  # deploy step will run only after manual approval
  deploy:
    docker:
      - image: "cimg/base:stable"
      # more setup needed for aws, node, elastic beanstalk
    steps:
      - node/install:
          node-version: '4.7' 
      - eb/setup
      - aws-cli/setup
      - checkout
      - run:
          name: Deploy App
          # TODO: Install, build, deploy in both apps
          command: |
            npm run deploy
            echo "# TODO: Install, build, deploy in both apps"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold